version: '3.8'
services:
  client:
    build:
      context: ../
      dockerfile: docker/Dockerfile.client
    ports:
      - "3000:3000"
    depends_on:
      - server
  server:
    build:
      context: ../
      dockerfile: docker/Dockerfile.server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/blog
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
